# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:58:27+00:00

from __future__ import annotations


from pydantic import BaseModel, Field


class PriceListMapItem(BaseModel):
    name: str
    exterior: str | None = None
    stat_trak: bool | None = Field(None, alias="statTrak")
    souvenir: bool | None = Field(None, alias="souvenir")
    lowest_price: float = Field(alias="lowestPrice")
    market_hash_name: str = Field(alias="marketHashName")
    quantity: int
    url: str | None = None
    doppler_class_name: str | None = Field(None, alias="dopplerClassName")


class PriceList(BaseModel):
    map: list[PriceListMapItem]
