# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:58:27+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class PriceListMapItem(BaseModel):
    name: Optional[str] = None
    exterior: Optional[str] = None
    stat_trak: Optional[bool] = Field(None, alias="statTrak")
    souvenir: Optional[bool] = None
    lowest_price: Optional[float] = Field(None, alias="lowestPrice")
    market_hash_name: Optional[str] = Field(None, alias="marketHashName")
    quantity: Optional[int] = None
    url: Optional[str] = None
    doppler_class_name: Optional[str] = Field(None, alias="dopplerClassName")


class PriceList(BaseModel):
    map: Optional[List[PriceListMapItem]]
