# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-12T11:03:52+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Sale(BaseModel):
    time: Optional[int] = None
    price: Optional[str] = None


class ResponseItem(BaseModel):
    name: Optional[str] = None
    appid: Optional[int] = None
    sales: Optional[List[Sale]] = None


class SalesHistoryMulti(BaseModel):
    success: Optional[bool] = None
    response: Optional[List[ResponseItem]] = None
