# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-12T11:03:44+00:00

from __future__ import annotations


from pydantic import BaseModel


class ResponseItem(BaseModel):
    time: int
    price: str


class SalesHistory(BaseModel):
    success: bool
    response: list[ResponseItem]
