# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:58:22+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class LowestPricesResponseItem(BaseModel):
    marketname: Optional[str]
    lowest_price: Optional[str]


class LowestPricesResponse(BaseModel):
    time_updated: Optional[int]
    appid: Optional[int]
    items: Optional[List[LowestPricesResponseItem]]


class LowestPrices(BaseModel):
    success: Optional[bool]
    response: Optional[LowestPricesResponse]
