# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:58:22+00:00

from __future__ import annotations

from datetime import datetime
from pydantic import BaseModel


class LowestPricesResponseItem(BaseModel):
    marketname: str
    lowest_price: float


class LowestPricesResponse(BaseModel):
    time_updated: datetime
    appid: int
    items: list[LowestPricesResponseItem]


class LowestPrices(BaseModel):
    success: bool
    response: LowestPricesResponse
