# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-12T11:03:44+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class ResponseItem(BaseModel):
    time: Optional[int] = None
    price: Optional[str] = None


class SalesHistory(BaseModel):
    success: Optional[bool] = None
    response: Optional[List[ResponseItem]] = None
