# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-12T11:03:52+00:00

from __future__ import annotations

from pydantic import BaseModel


class Sale(BaseModel):
    time: int
    price: str


class ResponseItem(BaseModel):
    name: str
    appid: int
    sales: list[Sale]


class SalesHistoryMulti(BaseModel):
    success: bool
    response: list[ResponseItem]
