# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:58:25+00:00

from __future__ import annotations
from pydantic import BaseModel


class PricesItem(BaseModel):
    market_hash_name: str | None
    volume: str | None
    price: str | None


class Prices(BaseModel):
    success: bool | None
    time: int | None
    currency: str | None
    items: list[PricesItem | None]
