# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:58:25+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class GetPricesItem(BaseModel):
    market_hash_name: Optional[str]
    volume: Optional[str]
    price: Optional[str]


class GetPrices(BaseModel):
    success: Optional[bool]
    time: Optional[int]
    currency: Optional[str]
    items: Optional[List[GetPricesItem]]
