# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:58:25+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, RootModel


class GetPricesGetPrice(BaseModel):
    item: Optional[str]
    phase: Optional[str] = None
    price: Optional[float]
    currency: Optional[str]
    count: Optional[int]
    url: Optional[str]


class GetPrices(RootModel[Optional[List[GetPricesGetPrice]]]):
    root: Optional[List[GetPricesGetPrice]]
