# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:58:25+00:00

from __future__ import annotations


from pydantic import BaseModel, RootModel


class Price(BaseModel):
    item: str
    phase: str | None = None
    price: float
    currency: str
    count: int
    url: str


class Prices(RootModel[list[Price]]):
    root: list[Price]
