# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:58:25+00:00

from __future__ import annotations


from pydantic import BaseModel, RootModel


class Price(BaseModel):
    item: str | None
    phase: str | None = None
    price: float | None
    currency: str | None
    count: int | None
    url: str | None


class Prices(RootModel[list[Price]]):
    root: list[Price]
