# generated by datamodel-codegen for CS.Money market prices mapping
from __future__ import annotations
from typing import Optional, List, Dict
from pydantic import BaseModel, RootModel


class Sticker(BaseModel):
    overprice: Optional[float]
    name: str
    position: int
    price: float
    wear: int
    img: str
    wikiLink: str


class MarketPriceItem(BaseModel):
    fullName: str
    type: int
    subtype: str
    quality: str
    isStatTrak: bool
    icon: str
    steamIcon: str
    preview: Optional[str]
    assetId: int
    price: float
    marketCount: int
    float: float
    stickers: Optional[List[Optional[Sticker]]]
    paintseed: Optional[int]


class MinPrices(RootModel[dict[str, MarketPriceItem]]):
    root: dict[str, MarketPriceItem]
