# generated by datamodel-codegen for CS.Money market prices mapping
from __future__ import annotations
from pydantic import BaseModel, RootModel, Field, field_validator


class Sticker(BaseModel):
    overprice: float | None
    name: str
    position: int
    price: float
    wear: int
    img: str
    wikiLink: str


class MarketPriceItem(BaseModel):
    fullName: str
    type: int
    subtype: str
    quality: str
    isStatTrak: bool
    icon: str
    steamIcon: str
    preview: str | None
    assetId: int
    price: float
    marketCount: int
    float: float
    stickers: list[Sticker | None] = Field(default_factory=list)
    paintseed: int | None

    @field_validator("stickers", mode="before")
    @classmethod
    def ensure_stickers_list(cls, v):
        if v is None:
            return []
        return v


class MinPrices(RootModel[dict[str, MarketPriceItem]]):
    root: dict[str, MarketPriceItem]
