# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:58:22+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field
from enum import Enum


class TxOperationType(Enum):
    Offer = "Offer"
    Order = "Order"


class LastSalesSale(BaseModel):
    price: Optional[str]
    date: Optional[str]
    tx_operation_type: Optional[TxOperationType] = Field(None, alias="txOperationType")
    offer_attributes: Optional[Dict[str, Any]] = Field(None, alias="offerAttributes")
    order_attributes: Optional[Dict[str, Any]] = Field(None, alias="orderAttributes")


class LastSales(BaseModel):
    sales: Optional[List[LastSalesSale]]
