# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:58:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field, RootModel

class TypeModel(Enum):
    item = 'item'
    offer = 'offer'
    target = 'target'
    class_ = 'class'
    airdrop = 'airdrop'
    sale = 'sale'
    product = 'product'
    
class StatusModel(Enum):
    default = 'default'
    active = 'active'
    inactive = 'inactive'
    in_transfer = 'in_transfer'
    sold = 'sold'
    recalled = 'recalled'
    unavailable = 'unavailable'
    locked = 'locked'

class GameType(Enum):
    blockchain = 'blockchain'
    steam = 'steam'

class ExtraDoc(Enum):
    viewAtSteam = 'viewAtSteam'
    quality = 'quality'
    exterior = 'exterior'
    category = 'category'
    tradeLock = 'tradeLock'
    tradeLockDuration = 'tradeLockDuration'
    stickers = 'stickers'
    itemType = 'itemType'
    floatValue = 'floatValue'
    inspectInGame = 'inspectInGame'
    tagName = 'tagName'
    hero = 'hero'
    gems = 'gems'
    rarity = 'rarity'
    serialNumber = 'serialNumber'
    ability = 'ability'
    videos = 'videos'
    subscribers = 'subscribers'
    growth = 'growth'
    nameColor = 'nameColor'
    backgroundColor = 'backgroundColor'
    tradable = 'tradable'
    withdrawable = 'withdrawable'
    depositable = 'depositable'
    offerId = 'offerId'
    orderId = 'orderId'
    isNew = 'isNew'
    groupId = 'groupId'
    gameId = 'gameId'
    name = 'name'
    categoryPath = 'categoryPath'
    class_ = 'class'
    collection = 'collection'
    grade = 'grade'
    type = 'type'

class Exterior(Enum):
    field_tested = 'field-tested'
    minimal_wear = 'minimal wear'
    battle_scarred = 'battle-scarred'
    well_worn = 'well-worn'
    factory_new = 'factory new'
    not_painted = 'not painted'

class CSSticker(BaseModel):
    image: str
    name: str

class Dota2Gem(BaseModel):
    image: str
    name: str
    type: str

class Prices(BaseModel):
    DMC: str
    USD: str

class Recommendations(BaseModel):
    d3: Prices
    d7: Prices
    d7Plus: Prices

class OwnerDetails(BaseModel):
    avatar: str
    id: str
    wallet: str

class Extra(BaseModel):
    ability: Optional[str] = None
    backgroundColor: Optional[str] = None
    category: Optional[str] = None
    categoryPath: str
    class_: Optional[List[str]] = Field(None, alias='class')
    collection: Optional[List[str]] = None
    exterior: Optional[Exterior] = None
    floatValue: Optional[float] = None
    gameId: str
    gems: Optional[List[Dota2Gem]] = None
    grade: Optional[str] = None
    groupId: Optional[str] = None
    growth: Optional[float] = None
    hero: Optional[str] = None
    inspectInGame: Optional[str] = None
    isNew: bool
    itemType: Optional[str] = None
    linkId: Optional[str] = None
    name: str
    nameColor: Optional[str] = None
    offerId: Optional[str] = None
    quality: Optional[str] = None
    rarity: Optional[str] = None
    serialNumber: Optional[int] = None
    stickers: Optional[List[CSSticker]] = None
    subscribers: Optional[int] = None
    tagName: Optional[str] = None
    tradable: bool
    tradeLock: Optional[int] = None
    tradeLockDuration: int
    type: Optional[str] = None
    videos: Optional[int] = None
    viewAtSteam: Optional[str] = None
    withdrawable: Optional[bool] = None

class Item(BaseModel):
    amount: int
    classId: str
    createdAt: int
    description: str
    discount: int
    extra: Extra
    extraDoc: Optional[ExtraDoc] = None
    gameId: str
    gameType: GameType
    image: str
    inMarket: bool
    instantPrice: Optional[Prices] = None
    instantTargetId: str
    itemId: str
    lockStatus: bool
    owner: str
    ownerDetails: OwnerDetails
    ownersBlockchainId: str
    price: Optional[Prices] = None
    recommendedPrice: Optional[Recommendations] = None
    slug: str
    status: StatusModel
    suggestedPrice: Optional[Prices] = None
    title: str
    type: TypeModel

class Total(BaseModel):
    offers: Optional[int]
    targets: Optional[int]
    closedTargets: Optional[int]

class GetMarketItems(BaseModel):
    cursor: Optional[str] = None
    objects: List[Item]
    total: Optional[Total] = None
