# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:58:22+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field
from enum import Enum


class TxOperationType(Enum):
    Offer = "Offer"
    Order = "Order"


class LastSalesSale(BaseModel):
    price: str | None
    date: str | None
    tx_operation_type: TxOperationType | None = Field(None, alias="txOperationType")
    offer_attributes: dict[str, Any | None] | None = Field(
        None, alias="offerAttributes"
    )
    order_attributes: dict[str, Any | None] | None = Field(
        None, alias="orderAttributes"
    )


class LastSales(BaseModel):
    sales: list[LastSalesSale | None]
