# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:58:28+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, RootModel


class ItemsItem(BaseModel):
    market_hash_name: Optional[str]
    currency: Optional[str]
    suggested_price: Optional[float] = None
    item_page: Optional[str]
    market_page: Optional[str]
    min_price: Optional[float] = None
    max_price: Optional[float] = None
    mean_price: Optional[float] = None
    median_price: Optional[float] = None
    quantity: Optional[int]
    created_at: Optional[int]
    updated_at: Optional[int]


class Items(RootModel[Optional[List[ItemsItem]]]):
    root: Optional[List[ItemsItem]]
