# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:58:28+00:00

from __future__ import annotations


from pydantic import BaseModel, RootModel


class ItemsItem(BaseModel):
    market_hash_name: str | None
    currency: str | None
    suggested_price: float | None = None
    item_page: str | None
    market_page: str | None
    min_price: float | None = None
    max_price: float | None = None
    mean_price: float | None = None
    median_price: float | None = None
    quantity: int | None
    created_at: int | None
    updated_at: int | None


class Items(RootModel[list[ItemsItem]]):
    root: list[ItemsItem]
