# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:58:29+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class GetMarketListingsSearchdata(BaseModel):
    query: Optional[str]
    search_descriptions: Optional[bool]
    total_count: Optional[int]
    pagesize: Optional[int]
    prefix: Optional[str]
    class_prefix: Optional[str]


class GetMarketListingsResultAssetDescription(BaseModel):
    appid: Optional[int]
    classid: Optional[str]
    instanceid: Optional[str]
    background_color: Optional[str]
    icon_url: Optional[str]
    tradable: Optional[int]
    name: Optional[str]
    name_color: Optional[str]
    type: Optional[str]
    market_name: Optional[str]
    market_hash_name: Optional[str]
    commodity: Optional[int]


class GetMarketListingsResult(BaseModel):
    name: Optional[str]
    hash_name: Optional[str]
    sell_listings: Optional[int]
    sell_price: Optional[int]
    sell_price_text: Optional[str]
    app_icon: Optional[str]
    app_name: Optional[str]
    asset_description: Optional[GetMarketListingsResultAssetDescription]
    sale_price_text: Optional[str]


class GetMarketListings(BaseModel):
    success: Optional[bool]
    start: Optional[int]
    pagesize: Optional[int]
    total_count: Optional[int]
    searchdata: Optional[GetMarketListingsSearchdata]
    results: Optional[List[GetMarketListingsResult]]
