# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:58:29+00:00

from __future__ import annotations


from pydantic import BaseModel


class MarketlistingsSearchdata(BaseModel):
    query: str | None
    search_descriptions: bool | None
    total_count: int | None
    pagesize: int | None
    prefix: str | None
    class_prefix: str | None


class MarketlistingsResultAssetDescription(BaseModel):
    appid: int | None
    classid: str | None
    instanceid: str | None
    background_color: str | None
    icon_url: str | None
    tradable: int | None
    name: str | None
    name_color: str | None
    type: str | None
    market_name: str | None
    market_hash_name: str | None
    commodity: int | None


class MarketlistingsResult(BaseModel):
    name: str | None
    hash_name: str | None
    sell_listings: int | None
    sell_price: int | None
    sell_price_text: str | None
    app_icon: str | None
    app_name: str | None
    asset_description: MarketlistingsResultAssetDescription | None
    sale_price_text: str | None


class Marketlistings(BaseModel):
    success: bool | None
    start: int | None
    pagesize: int | None
    total_count: int | None
    searchdata: MarketlistingsSearchdata | None
    results: list[MarketlistingsResult | None]
