# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:58:29+00:00

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel


class Pricehistory(BaseModel):
    success: Optional[bool]
    price_prefix: Optional[str]
    price_suffix: Optional[str]
    prices: Optional[List[List[Union[float, str]]]]
