# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:58:29+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class GetInventoryAsset(BaseModel):
    appid: Optional[int] = None
    contextid: Optional[str] = None
    assetid: Optional[str] = None
    classid: Optional[str] = None
    instanceid: Optional[str] = None
    amount: Optional[str] = None


class GetInventoryDescriptionDescription(BaseModel):
    type: Optional[str] = None
    value: Optional[str] = None
    name: Optional[str] = None
    color: Optional[str] = None


class GetInventoryDescriptionAction(BaseModel):
    link: Optional[str] = None
    name: Optional[str] = None


GetInventoryDescriptionMarketAction = GetInventoryDescriptionAction


class GetInventoryDescriptionTag(BaseModel):
    category: Optional[str] = None
    internal_name: Optional[str] = None
    localized_category_name: Optional[str] = None
    localized_tag_name: Optional[str] = None
    color: Optional[str] = None


class GetInventoryDescription(BaseModel):
    appid: Optional[int] = None
    classid: Optional[str] = None
    instanceid: Optional[str] = None
    currency: Optional[int] = None
    background_color: Optional[str] = None
    icon_url: Optional[str] = None
    descriptions: Optional[List[GetInventoryDescriptionDescription]] = None
    tradable: Optional[int] = None
    actions: Optional[List[GetInventoryDescriptionAction]] = None
    name: Optional[str] = None
    name_color: Optional[str] = None
    type: Optional[str] = None
    market_name: Optional[str] = None
    market_hash_name: Optional[str] = None
    market_actions: Optional[List[GetInventoryDescriptionMarketAction]] = None
    commodity: Optional[int] = None
    market_tradable_restriction: Optional[int] = None
    market_marketable_restriction: Optional[int] = None
    marketable: Optional[int] = None
    tags: Optional[List[GetInventoryDescriptionTag]] = None


class GetInventory(BaseModel):
    assets: Optional[List[GetInventoryAsset]] = None
    descriptions: Optional[List[GetInventoryDescription]] = None
    total_inventory_count: Optional[int] = None
    success: Optional[int] = None
    rwgrsn: Optional[int] = None
