# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:58:29+00:00

from __future__ import annotations


from pydantic import BaseModel


class Searchdata(BaseModel):
    query: str | None
    search_descriptions: bool | None
    total_count: int | None
    pagesize: int | None
    prefix: str | None
    class_prefix: str | None


class AssetDescription(BaseModel):
    appid: int
    classid: str
    instanceid: str
    background_color: str
    icon_url: str
    tradable: int
    name: str
    name_color: str
    type: str
    market_name: str
    market_hash_name: str
    commodity: int


class Result(BaseModel):
    name: str
    hash_name: str
    sell_listings: int
    sell_price: int
    sell_price_text: str
    app_icon: str
    app_name: str
    asset_description: AssetDescription
    sale_price_text: str | None


class MarketPage(BaseModel):
    success: bool
    start: int
    pagesize: int
    total_count: int
    searchdata: Searchdata
    results: list[Result]
