# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:58:29+00:00

from __future__ import annotations

from pydantic import BaseModel


class Pricehistory(BaseModel):
    success: bool | None
    price_prefix: str | None
    price_suffix: str | None
    prices: list[list[float | str | None]]
