# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:58:29+00:00

from __future__ import annotations


from pydantic import BaseModel


class InventoryAsset(BaseModel):
    appid: int | None = None
    contextid: str | None = None
    assetid: str | None = None
    classid: str | None = None
    instanceid: str | None = None
    amount: str | None = None


class InventoryDescriptionDescription(BaseModel):
    type: str | None = None
    value: str | None = None
    name: str | None = None
    color: str | None = None


class InventoryDescriptionAction(BaseModel):
    link: str | None = None
    name: str | None = None


InventoryDescriptionMarketAction = InventoryDescriptionAction


class InventoryDescriptionTag(BaseModel):
    category: str | None = None
    internal_name: str | None = None
    localized_category_name: str | None = None
    localized_tag_name: str | None = None
    color: str | None = None


class InventoryDescription(BaseModel):
    appid: int | None = None
    classid: str | None = None
    instanceid: str | None = None
    currency: int | None = None
    background_color: str | None = None
    icon_url: str | None = None
    descriptions: list[InventoryDescriptionDescription | None] | None = None
    tradable: int | None = None
    actions: list[InventoryDescriptionAction | None] | None = None
    name: str | None = None
    name_color: str | None = None
    type: str | None = None
    market_name: str | None = None
    market_hash_name: str | None = None
    market_actions: list[InventoryDescriptionMarketAction | None] | None = None
    commodity: int | None = None
    market_tradable_restriction: int | None = None
    market_marketable_restriction: int | None = None
    marketable: int | None = None
    tags: list[InventoryDescriptionTag | None] | None = None


class Inventory(BaseModel):
    assets: list[InventoryAsset | None] | None = None
    descriptions: list[InventoryDescription | None] | None = None
    total_inventory_count: int | None = None
    success: int | None = None
    rwgrsn: int | None = None
