from __future__ import annotations

from pydantic import BaseModel, Field


class LatestRatesRates(BaseModel):
    USD: float
    AED: float
    AFN: float
    ALL: float
    AMD: float
    ANG: float
    AOA: float
    ARS: float
    AUD: float
    AWG: float
    AZN: float
    BAM: float
    BBD: float
    BDT: float
    BGN: float
    BHD: float
    BIF: float
    BMD: float
    BND: float
    BOB: float
    BRL: float
    BSD: float
    BTN: float
    BWP: float
    BYN: float
    BZD: float
    CAD: float
    CDF: float
    CHF: float
    CLP: float
    CNY: float
    COP: float
    CRC: float
    CUP: float
    CVE: float
    CZK: float
    DJF: float
    DKK: float
    DOP: float
    DZD: float
    EGP: float
    ERN: float
    ETB: float
    EUR: float
    FJD: float
    FKP: float
    FOK: float
    GBP: float
    GEL: float
    GGP: float
    GHS: float
    GIP: float
    GMD: float
    GNF: float
    GTQ: float
    GYD: float
    HKD: float
    HNL: float
    HRK: float
    HTG: float
    HUF: float
    IDR: float
    ILS: float
    IMP: float
    INR: float
    IQD: float
    IRR: float
    ISK: float
    JEP: float
    JMD: float
    JOD: float
    JPY: float
    KES: float
    KGS: float
    KHR: float
    KID: float
    KMF: float
    KRW: float
    KWD: float
    KYD: float
    KZT: float
    LAK: float
    LBP: float
    LKR: float
    LRD: float
    LSL: float
    LYD: float
    MAD: float
    MDL: float
    MGA: float
    MKD: float
    MMK: float
    MNT: float
    MOP: float
    MRU: float
    MUR: float
    MVR: float
    MWK: float
    MXN: float
    MYR: float
    MZN: float
    NAD: float
    NIO: float
    NOK: float
    NPR: float
    NZD: float
    OMR: float
    PAB: float
    PEN: float
    PGK: float
    PHP: float
    PKR: float
    PLN: float
    PYG: float
    QAR: float
    RON: float
    RSD: float
    RUB: float
    RWF: float
    SAR: float
    SBD: float
    SCR: float
    SDG: float
    SEK: float
    SGD: float
    SHP: float
    SLE: float
    SOS: float
    SRD: float
    SSP: float
    STN: float
    SYP: float
    SZL: float
    THB: float
    TJS: float
    TMT: float
    TND: float
    TOP: float
    TRY: float
    TTD: float
    TVD: float
    TWD: float
    TZS: float
    UAH: float
    UGX: float
    UYU: float
    UZS: float
    VES: float
    VND: float
    VUV: float
    WST: float
    XAF: float
    XCD: float
    XCG: float
    XDR: float
    XOF: float
    XPF: float
    YER: float
    ZAR: float
    ZMW: float
    ZWL: float


class LatestRates(BaseModel):
    result: str
    provider: str
    documentation: str
    terms_of_use: str
    time_last_update_unix: int
    time_last_update_utc: str
    time_next_update_unix: int
    time_next_update_utc: str
    time_eol_unix: int
    base_code: str
    rates: LatestRatesRates
