# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:27:19+00:00

from __future__ import annotations

from typing import Dict, List, Optional, Union

from pydantic import BaseModel


class AssetClassInfoItemDescriptions(BaseModel):
    type: Optional[str] = None
    value: Optional[str] = None
    color: Optional[str] = None
    name: Optional[str] = None


class AssetClassInfoItemActions(BaseModel):
    type: Optional[str] = None
    name: Optional[str] = None
    link: Optional[str] = None


class AssetClassInfoItemMarketAction(AssetClassInfoItemActions):
    pass


class AssetClassInfoItemTags(BaseModel):
    internal_name: Optional[str] = None
    name: Optional[str] = None
    category: Optional[str] = None
    category_name: Optional[str] = None
    color: Optional[str] = None


class AssetClassInfoItem(BaseModel):
    classid: Optional[str] = None
    icon_url: Optional[str] = None
    icon_url_large: Optional[str] = None
    icon_drag_url: Optional[str] = None
    name: Optional[str] = None
    market_hash_name: Optional[str] = None
    market_name: Optional[str] = None
    name_color: Optional[str] = None
    background_color: Optional[str] = None
    type: Optional[str] = None
    tradable: Optional[str] = None
    marketable: Optional[str] = None
    commodity: Optional[str] = None
    market_tradable_restriction: Optional[str] = None
    market_marketable_restriction: Optional[str] = None
    descriptions: Optional[List[AssetClassInfoItemDescriptions]] = None
    owner_descriptions: Optional[str] = None
    actions: Optional[List[AssetClassInfoItemActions]] = None
    market_actions: Optional[List[AssetClassInfoItemMarketAction]] = None
    tags: Optional[List[AssetClassInfoItemTags]] = None


class AssetClassInfoError(BaseModel):
    error: Optional[str] = None
    success: Optional[bool] = None


class AssetClassInfo(BaseModel):
    result: Optional[Union[Dict[str, AssetClassInfoItem], AssetClassInfoError]] = None
    success: Optional[bool] = None
