# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-09T20:51:56+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class PlayerSummariesResponsePlayer(BaseModel):
    steamid: Optional[str]
    communityvisibilitystate: Optional[int]
    profilestate: Optional[int]
    personaname: Optional[str]
    profileurl: Optional[str]
    avatar: Optional[str]
    avatarmedium: Optional[str]
    avatarfull: Optional[str]
    avatarhash: Optional[str]
    personastate: Optional[int]
    primaryclanid: Optional[str]
    timecreated: Optional[int]
    personastateflags: Optional[int]
    loccountrycode: Optional[str]
    locstatecode: Optional[str]


class PlayerSummariesResponse(BaseModel):
    players: Optional[List[PlayerSummariesResponsePlayer]]


class PlayerSummaries(BaseModel):
    response: Optional[PlayerSummariesResponse]
